name: shuats-quiz-app-postgres

services:
    postgres:
        image: postgres:16-alpine
        container_name: shuats-quiz-app-postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: quizapp
        ports:
            - '5433:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data
        restart: unless-stopped
        networks:
            - quiz-app-network

networks:
    quiz-app-network:
        driver: bridge

volumes:
    postgres_data:
        driver: local
